apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          value: {{ .Values.env.DB_USER }}
        - name: DB_PASS
          value: {{ .Values.env.DB_PASS }}
        - name: DB_HOST
          value: {{ .Values.env.DB_HOST }}
        - name: DB_NAME
          value: {{ .Values.env.DB_NAME }}
