image:
  repository: flaskapp
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  DB_USER: user
  DB_PASS: password
  DB_HOST: my-sql-instance
  DB_NAME: test-db
