name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone ${{secrets.GCP_REGION}} --project ${{secrets.GCP_PROJECT_ID}}

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Deploy application
        run: |
          helm upgrade --install my-app ./my-app-chart --namespace default --create-namespace --wait

      - name: Push Helm chart to storages
        run: |
          gsutil cp ./my-app-chart/*.tgz gs://<your-bucket-name>/
