name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

    - name: Authenticate with service account and set project
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/service-key.json
        gcloud auth activate-service-account --key-file=$HOME/service-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GCP_REGION }}

    - name: Install kubectl-credential-gke plugin
      run: |
        gcloud components install kubectl-credential-gke

    - name: Verify Kubernetes connection
      run: kubectl get pods --all-namespaces

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --install app ./app --namespace default --create-namespace --wait
