name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

   
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GCP_REGION }}

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

    - name: Deploy RBAC configurations
      run: |
        kubectl apply -f service-account-permissions.yaml

    - name: Deploy application using Helm
      run: |
        helm upgrade --install flask-app ./flask-app --namespace default

    - name: Push Helm chart to GCS
      run: |
        gsutil cp -r ./flask-app gs://${{ secrets.GCS_BUCKET }}/charts/
